# Generated by Django 4.2.8 on 2023-12-26 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='textoComentario',
            new_name='comentario',
        ),
    ]
