# Generated by Django 4.2.8 on 2023-12-26 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_categoria_noticia_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
