# Generated by Django 4.2.8 on 2023-12-26 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_remove_noticia_categoria_delete_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='editado',
            field=models.DateField(auto_now=True, verbose_name='editado'),
        ),
    ]
